// src/app/dashboard/dashboard/components/quote/quote.component.ts
import { ChangeDetectionStrategy, Component, inject } from '@angular/core'
import { QuoteStore } from '@app/store'

@Component({
  selector: 'app-quote',
  templateUrl: './quote.component.html',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class QuoteComponent {
  readonly store = inject(QuoteStore)
  quote = this.store.quote
}

@let quote = quote$ | async;

@if (quote) {
  <div class='flex items-center justify-center p-4'>
    <div class='max-w-lg rounded-lg bg-gray-100 p-6 shadow-lg dark:bg-gray-800'>
      <p class='mb-4 text-2xl text-gray-900 dark:text-gray-200'>
        &ldquo;{{ quote?.phrase }}&rdquo;
      </p>
      <p class='text-right text-lg font-semibold text-gray-700 dark:text-gray-100'>
        &mdash; {{ quote?.character }} en {{ quote?.movie }}
      </p>
    </div>
  </div>
}

// src/components/Quote.tsx
import { useFetchData } from '@hooks/useFetchData'
import LoadingSpinner from '@components/LoadingSpinner.tsx'

interface PhraseData {
  phrase: string;
  movie: string;
  character: string;
}

export default function Quote() {
  const { data: result, error } = useFetchData<PhraseData>('/api/get-quote')

  if (error) return null
  if (!result) <LoadingSpinner />

  return result && (
    <div className="flex items-center justify-center p-4">
      <div className="bg-gray-200 dark:bg-gray-900 p-6 rounded-lg shadow-lg max-w-lg">
        <p className="text-2xl text-gray-900 dark:text-gray-200 mb-4">
          &ldquo;{result.phrase}&rdquo;
        </p>
        <p className="text-right text-lg font-semibold text-gray-700 dark:text-gray-100">
          &mdash; {result.character} en {result.movie}
        </p>
      </div>
    </div>
  )
}
